### ISSUE TITLE
3 FLOPs StarReLU

### ISSUE THREAD

**Issue by rydenisbak** [sail-sg/metaformer#5]
Hello, thanks for the great work!

I want to say, if scale in StarReLU are positive number, you can merge it to weights of the previous layer after training.
After merging StarReLU will take only 3 FLOPs for version with scale and bias.

I checked all scales in caformer_s18.pth pretrained in ImageNet 1k and figure out that all scales are positive.

May be we need some modification
```python
class StarPosScaleReLU(StarReLU):
  def forward(self, x):
    return torch.abs(self.scale) * self.relu(x)**2 + self.bias
```

for totally certain that all scales will be positive.

I will check other pretrain weights and do experiment with `StarPosScaleReLU`

**Comment by yuweihao** [comment]
Hi @rydenisbak ,

Many thanks for your attention :)

Actually, no matter whether the value is positive or not, the scale of StarReLU can be merged into the next FC/Conv at the inference phase, because StarReLU can also be written as 
`(relu(x) ** 2 + b') * s'`.

Since in my original implementation, StarReLU is implemented as 
`relu(x) ** 2 * s + b`,
so we can obtain
`s' = s; b'=b/s`.

**Comment by rydenisbak** [comment]
Exactly, you are right, very easy and good  idea, thanks!

🙈 Inertia of thinking...
