### ISSUE TITLE
Why does the classifier head use a different non-linearity from the rest of the architecture?

### ISSUE THREAD

**Issue by JRestom** [sail-sg/metaformer#6]
Checking the code I found the head uses squared-ReLU instead of star-ReLU and after some experiments replacing it, I found the performance actually decreased. Was there a reason to select squared-ReLU specifically for the classifier head?

**Comment by yuweihao** [comment]
Hi, @JRestom , thanks for your attention.

The reason is that a `LayerNorm` is put after the activation, before the final FC (see this [line](https://github.com/sail-sg/metaformer/blob/main/metaformer_baselines.py#L404)), to stabilize training. LayerNorm can normalize the input distribution, so using Squared ReLU is enough in this case.
